Repository EOX-A/EOxElements, pull requests merged in 2024-12, with the labels that each got.

#1407 fix: chips for pre-set filters
  elements/itemfilter/src/components/filters/range.js
  elements/itemfilter/src/methods/filters/range.js
  elements/itemfilter/src/methods/itemfilter/filter-apply.js
Labels: bug

#1422 fix: listen for click on entire result instead of just title
  elements/itemfilter/src/methods/results/create.js
Labels: bug

#1425 Fix: Storytelling navigation in mobile view
  elements/storytelling/src/helpers/render-html-string.js
  elements/storytelling/src/style.eox.js
Labels: enhancement

#1441 feat: date/time display format
  elements/timecontrol/src/main.js
  elements/timecontrol/stories/format.js
  elements/timecontrol/stories/index.js
  elements/timecontrol/stories/timecontrol.stories.js
  elements/timecontrol/test/cases/index.js
  elements/timecontrol/test/cases/load-date-format.js
  elements/timecontrol/test/general.cy.js
Labels: enhancement, timecontrol

#1433 Fix: Changed nav content position from bottom to top
  elements/storytelling/src/style.eox.js
Labels: bug
